version: '3.1'
services:
  postgresql:
    container_name: postgres-std_inf_sys
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
  redis:
    container_name: redis-std_inf_sys
    image: redis
    ports:
      - '6379:6379'