version: '3.1'
services:
  api_service:
    build: .
    ports:
      - "8080:8080"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql_db:5432/School
        - SPRING_CACHE_HOST=redis_db
        - SPRING_FLYWAY_URL=jdbc:postgresql://postgresql_db:5432/School
    depends_on:
        - postgresql_db
        - redis_db
  postgresql_db:
    container_name: postgres-std_inf_sys
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres
      POSTGRES_DB: School
    ports:
      - "5432:5432"
  redis_db:
    container_name: redis-std_inf_sys
    image: redis
    ports:
      - '6379:6379'