CREATE TABLE IF NOT EXISTS public.lecture_note
(
    lecture_note_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    live_lesson_id  BIGINT,
    CONSTRAINT pk_lecture_note PRIMARY KEY (lecture_note_id),
    CONSTRAINT FK_LECTURE_NOTE_ON_LIVE_LESSON_ID FOREIGN KEY (live_lesson_id) REFERENCES public.live_lesson (live_lesson_id)
);

CREATE TABLE IF NOT EXISTS public.weekly_notes
(
    weekly_notes_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lecture_note_id BIGINT,
    week_number     INTEGER,
    description     VARCHAR(255),
    CONSTRAINT pk_weekly_notes PRIMARY KEY (weekly_notes_id),
    CONSTRAINT FK_WEEKLY_NOTES_ON_LECTURE_NOTE_ID FOREIGN KEY (lecture_note_id) REFERENCES public.lecture_note (lecture_note_id)
);

CREATE TABLE IF NOT EXISTS public.file
(
    weekly_notes_id BIGINT NOT NULL,
    file_name       VARCHAR(255),
    file_extension  VARCHAR(255),
    content_type    VARCHAR(255),
    file_size       BIGINT,
    cloud_path      VARCHAR(255),
    download_url    VARCHAR(255),
    CONSTRAINT "fk_fıle_on_weekly_notes" FOREIGN KEY (weekly_notes_id) REFERENCES public.weekly_notes (weekly_notes_id)
);



