CREATE TABLE IF NOT EXISTS public.role
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    tck_no     VARCHAR(255),
    tel_no     VARCHAR(255),
    e_mail     VARCHAR(255),
    address    VARCHAR(255),
    password   VARCHAR(255),
    role_id    BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uc_user_e_maıl UNIQUE (e_mail),
    CONSTRAINT uc_user_tck_no UNIQUE (tck_no),
    CONSTRAINT uc_user_tel_no UNIQUE (tel_no),
    CONSTRAINT FK_USER_ON_ROLE_ID FOREIGN KEY (role_id) REFERENCES public.role (role_id)
);