CREATE TABLE IF NOT EXISTS public.period
(
    period_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    CONSTRAINT "pk_period" PRIMARY KEY (period_id)
);

ALTER TABLE public.live_lesson
    DROP COLUMN is_first_period;

ALTER TABLE public.live_lesson
    ADD COLUMN period_id BIGINT;

ALTER TABLE public.live_lesson
    ADD CONSTRAINT FK_LIVE_LESSON_ON_PERIOD_ID FOREIGN KEY (period_id) REFERENCES public.period (period_id);


INSERT INTO public.period (period_id, name)
VALUES (1, 'Fall'),
       (2, 'Spring'),
       (3, 'Summer');